@HotelOps.Api_HostAddress = http://localhost:5091
@RomId = 00000000-0000-0000-0000-000000000000

GET {{HotelOps.Api_HostAddress}}/api/helse
Accept: application/json

###

GET {{HotelOps.Api_HostAddress}}/api/rom
Accept: application/json

###

POST {{HotelOps.Api_HostAddress}}/api/rom
Content-Type: application/json

{
  "nummer": "101",
  "etasje": 1
}

###

PATCH {{HotelOps.Api_HostAddress}}/api/rom/{{RomId}}/rengjoring/marker-skitten

###

PATCH {{HotelOps.Api_HostAddress}}/api/rom/{{RomId}}/rengjoring/start

###

PATCH {{HotelOps.Api_HostAddress}}/api/rom/{{RomId}}/rengjoring/fullfor

###

# Bruk et rom som er skittent eller under rengjøring.
PATCH {{HotelOps.Api_HostAddress}}/api/rom/{{RomId}}/rengjoring/planlegg
Content-Type: application/json

{
  "ansvarligRenholder": "Kari",
  "prioritet": "Haster"
}

###
