// <auto-generated />
using System;
using HotelOps.Infrastruktur.Datalagring;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelOps.Infrastruktur.Datalagring.Migreringer
{
    [DbContext(typeof(HotellDbContext))]
    [Migration("20260831112013_OpprettRom")]
    partial class OpprettRom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelOps.Domene.Romadministrasjon.Rom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Beleggsstatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Driftsstatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Etasje")
                        .HasColumnType("integer");

                    b.Property<string>("Nummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rengjøringsstatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Nummer")
                        .IsUnique();

                    b.ToTable("Rom", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
